### ISSUE TITLE
code for grad-cam

### ISSUE THREAD

**Issue by tjwy** [czifan/MuMo#1]
Fantastic work! 
I was wondering if you could share some insights or code regarding the Grad-CAM visualization part. 
I'm working on a multimodal project and the results from visualizing the MRI images with Grad-CAM look not so good. Thanks for any response！

**Comment by czifan** [comment]
> Fantastic work! I was wondering if you could share some insights or code regarding the Grad-CAM visualization part. I'm working on a multimodal project and the results from visualizing the MRI images with Grad-CAM look not so good. Thanks for any response！

Thank you for your interest in our work!

For our Grad-CAM visualizations, we referred to this implementation: [gradcam_plus_plus-pytorch](https://github.com/1Konny/gradcam_plus_plus-pytorch/blob/master/gradcam.py).

I hope this helps with your multimodal project!
