### ISSUE TITLE
What's the meaning of Label？

### ISSUE THREAD

**Issue by Wangrui-berry** [czifan/MuMo#3]
Is the label about the response to Anti-HER2 treatment? And what dose the label in the excel (supplemental material) of "-1" (there is 0, 1, -1) represent?

**Comment by tjwy** [comment]
I'm also curious about the convert_label function. It seems that 1 represents a response, 0 represents no response, and -1 represents uncertainty. But, I'm puzzled by the judgment based on the cutoff values of OS and PFS.

**Comment by czifan** [comment]
> Is the label about the response to Anti-HER2 treatment? And what dose the label in the excel (supplemental material) of "-1" (there is 0, 1, -1) represent?

Sorry for the late response.

To clarify:
1. Label "0" represents non-responder, "1" represents responder, and "-1" indicates an indeterminate response.
2. For treatment response prediction, only labels {0, 1} are used for analysis. However, for survival analysis, all data points, including "-1", are included in the analysis.

Hope this helps!

**Comment by czifan** [comment]
> I'm also curious about the convert_label function. It seems that 1 represents a response, 0 represents no response, and -1 represents uncertainty. But, I'm puzzled by the judgment based on the cutoff values of OS and PFS.

1. To clarify:
   - Label "0" represents non-responder, "1" represents responder, and "-1" indicates an indeterminate response.
   - For treatment response prediction, only labels {0, 1} are used for analysis. However, for survival analysis, all data points, including "-1", are included in the analysis.

2. The OS and PFS cutoff values are determined based on the predicted probabilities for labels {0, 1} using the Youden index on the ROC curve.

Hope this helps!
